### ISSUE TITLE
Support for RadListView?

### ISSUE THREAD

**Issue by NordlingArt** [bradmartin/nativescript-pulltorefresh#17]
I have switched from regular ListView to RadListView recently because it's just more customizable. However, I lost this plugin while doing so because it is complaining about there being no ScrollView within. I know that there is already a pull-to-refresh feature in RadListView, but it is clumsy and destroys the user experience. The developers for Telerik-UI don't answer issues very often either...

I'm only asking for this if it's a simple task to fix. Otherwise, I'll find other options :)

Thanks in advance

**Comment by bradmartin** [comment]
Hi @NordlingArt I've not tried this with the RLV. Like you said since it has pull to refresh support already, I never attempted it 😄 . With that said, I imagine it's possible if you adjust your layout but not certain on that. If you want to share your XML I can throw out some suggestions to try. Without seeing it, things I would try is just wrapping different items in different layouts. Maybe Use the pull-to-refresh inside a stacklayout and then position the RLV inside of another stacklayout. I've had to do that with a few apps myself to get it working just right with different layout approaches, sorry it's not a rock solid approach :) just trial and error 😛  Hopefully adjusting the layout helps some though.

Sorry about the Telerik-UI support on issues, there is some general confusion regarding where to post issues. I've pinged some of the Telerik employees about this and it's been brought up before so hopefully soon there is a clear guideline on posting issues for the TelerikUI stuff.

**Comment by NordlingArt** [comment]
@bradmartin - I figured that I wanted my a customized refresh control and not the native one. So I had to make my own pull-to-refresh module that's compatible with RadListView 🙂

Yeah, I posted an issue about this over there. No answer hehe.

**Comment by EddyVerbruggen** [comment]
@NordlingArt Would you be willing to share your solution perhaps?

**Comment by NordlingArt** [comment]
@EddyVerbruggen - Sure thing. Though I'm currently migrating my plugins to 3.0, so I cannot share it yet. I'll post here once it's ready.

**Comment by vultix** [comment]
@EddyVerbruggen @NordlingArt Is there any update to this?  I'm running into the same problem.

**Comment by EddyVerbruggen** [comment]
Hey @vultix, I tweaked the appearance of the pulltorefresh and loadmore indicators for iOS this way:

https://gist.github.com/EddyVerbruggen/4087b951e432f10769327cac8cb32ed1

**Comment by vultix** [comment]
@EddyVerbruggen Thank you very much!

**Comment by bradmartin** [comment]
Closed via https://github.com/bradmartin/nativescript-pulltorefresh/pull/49
