### ISSUE TITLE
this plugin is not compatible with scrollview

### ISSUE THREAD

**Issue by GodShuning** [bradmartin/nativescript-pulltorefresh#26]

**Comment by celsomtrindade** [comment]
Running into same issue. When using it with ScrollView or ListView, when trying to scroll back to the top it will refresh the page, ven when touching the screen at the very bottom. I'm using it with angular as well.

But I noticed it only happens when using with more layout definitions. For example, the code below works as expected:

    <PullToRefresh (refresh)="refreshPage($event)">
        <ListView [items]="itemList" *ngIf="itemList.length > 0">
            <ng-template let-item="item">
                <Label [text]="item.name"></Label>
            </ng-template>
        </ListView>
    </PullToRefresh>

However, this code here doesn't:

    <PullToRefresh (refresh)="refreshPage($event)">
        <FlexboxLayout flexDirection="column">
            <ListView [items]="itemList" *ngIf="itemList.length > 0">
                <ng-template let-item="item">
                    <Label [text]="item.name"></Label>
                </ng-template>
            </ListView>

            <Label text="Some other content"></Label>
        </FlexboxLayout>
    </PullToRefresh>

Since there isn't much in the docs, I don't know if this is the expected behavior or if needs to fix something.

**Comment by bradmartin** [comment]
I think this mainly affects iOS correct? I recall having to adjust layouts for iOS to work. This line is all I recall, maybe @PeterStaev can provide some insight on the specifics here for iOS 😄 
I don't recall having any layout issues with Android but it's been awhile since I've used this one.

**Comment by PeterStaev** [comment]
The thing about iOS is that unlike Android you cannot use the pull to refresh functionality on any view, because the whole UI thing is rendered in `UIScrollView`. On Android it is just a separate UI element that is rendered at the top of any view, so it is independent. That's why for iOS the content of the pull to refresh needs to be a descendant of `UIScrollView`. In terms of {N} this means that  inside the `PullToRefresh` you must have `ScrollView` or `ListView`. Also works with some plugins - for example my `GridView` plugin.

**Comment by celsomtrindade** [comment]
For me this was happening on Android, I can't test it on IOS since I don't own one. Also, like I said, it only has a different behavior under the second template structure, and the pull refresh does work, but it blocks the scroll to top.

**Comment by bradmartin** [comment]
Realized I forgot to paste the line from the iOS file like 😄 @PeterStaev but thanks for chiming in on the iOS specifics. @celsomtrindade when you say it `blocks the scroll to top` you mean you can't scroll back to the top of the list, correct?

**Comment by celsomtrindade** [comment]
I can test it, but not very soon because I'm away. I'll try to give a feedback by tomorrow.

But that's correct, I can't scroll to the top of the page because when I try to do it, it activate the `pull to refresh`.

I'll try to play around with your tips and see if I can work around this. Not a big issue.

**Comment by simonox** [comment]
If I put it around a ScrollView under iOS pull-to-refresh is not working (no spinner, no refresh event).

```
        <PullToRefesh (refresh)="refresh()">
            <ScrollView #scrollView>
                <StackLayout class="baseLayout">
                       <!-- some content -->
                </StackLayout>
            </ScrollView>
        </PullToRefesh>
```

**Comment by cerireyhan** [comment]
@celsomtrindade Hi, I'm having a similar problem. I have a listview and a label (to display if the list is empty) inside pull-to-refresh however they can't be inside the same scrollview. Do you have a solution for your problem?

**Comment by william-levi** [comment]
+ 1 any workaround for this ? i'm also using scrollview

**Comment by tarantelklient** [comment]
+1

I have got the same problem atm. I want to refresh a view and have ScrollView inside the PullToRefresh :/

**Comment by markosole** [comment]
Hi guys, looks like this is still a problem. It works fine with Repeater and RadListView, but does not with ListView. I did not find any workaround. I m thinking to try with checking scroll position (check this out for idea: https://www.youtube.com/watch?v=k9cxGlAlo4s&t=1029s). All we need is to check scroll position and enable or disable plugin with **visibility="{{ (enabled !== 'yes' ? 'hidden': 'visible') }}"**
No idea if this and how this is going to work.
